version: 1.0.0.{build}

image:
 - Visual Studio 2019

install:
 - c:\msys64\usr\bin\pacman -Syu --noconfirm
 - c:\msys64\usr\bin\pacman -Syu --noconfirm
 - c:\msys64\usr\bin\pacman -S --noconfirm --needed make mingw-w64-x86_64-toolchain mingw-w64-x86_64-gcc mingw-w64-x86_64-fltk

build_script:
 - cd %APPVEYOR_BUILD_FOLDER%
 - c:\msys64\usr\bin\bash -c "PATH=/mingw64/bin:/bin:/usr/bin mkdir -p bin"
 - c:\msys64\usr\bin\bash -c "PATH=/mingw64/bin:/bin:/usr/bin make -f Makefile.mingw clean all TRACE=1"
 - c:\msys64\usr\bin\bash -c "PATH=/mingw64/bin:/bin:/usr/bin make -f Makefile.mingw clean all"

artifacts:
 - path: bin\vkvm.exe
   name: vkvm-binaries
